node ("ec2"){
	stage("checkout"){
		checkout([$class: 'GitSCM', 
		branches: [[name: '*/main']], 
		extensions: [], 
		userRemoteConfigs: [[credentialsId: 'cdffa240-45c6-4d63-b071-47a3eb6c756f', 
		url: 'https://github.com/S2rg45/dev-cicd']]])
	} 
	stage("terraform-init"){
			sh "terraform init -backend-config=backend.conf"
	}
}
